### ISSUE TITLE
Consider skipping some zooms (with overstuffing remaining zooms)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1006]
In Tangram-chat a user suggested an option to overstuff tiles at certain zooms so they could be reused at the next zooms, reducing number of over-the-wire fetches and overall tile cache size. We already set max_zoom to 16 a while back. 

The user suggested only providing zooms `4,10,15,19`. We stop at zoom 16 by default. 

One option is to skip every other zoom: `0,2,4,6,8,10,12,14,16`. 

Skipping more zooms should be possible, but I think only 1 or 3 more skipping max, eg: `0,2,5,7,10,13,14,16`?

**Comment by zerebubuth** [comment]
It's a trade-off between tile size and number of requests.

When looking at a "non-skipped" zoom, each tile is more detailed than necessary, which means the more time, data, memory and processing power spent to download the tile, but having paid that cost, there's no further cost to zooming in. At a "skipped" zoom, the tiles are "larger" which means there's a cost for stuff that's off-screen.

The flip-side to the extra cost is the reduced number of HTTP requests, themselves a source of latency, and (likely) increased cache hit ratio.

It's pretty hard to tell how much of one we'd be trading for the other without knowing the specifics of the platform we're targeting, e.g: a moving mobile phone on a 2G network somewhere rural, or a stationary mobile phone on a 4G network in a city.

**Comment by bcamper** [comment]
I am also interested in pursuing, either as an alternative (and/or in conjunction with this), the concept of larger screen area tiles, e.g. 512px or 1024px tiles (vs. the traditional raster 256px size). This would have an immediate 4x reduction in network requests for all zoom levels on all renderers, and has other benefits depending on the renderer -- for Tangram (and presumably most GL renderers), it also significantly reduces the GL state change / draw call overhead by reducing many of those calls by 4x as well.

So I think that is probably a more promising thing to try first. Some of this can be prototyped client-side without any server changes, though to get actual benchmarks we would need to mock something up server-side too.

**Comment by zerebubuth** [comment]
It would be super-interesting to know approximately what fraction of tiles are actually displayed. Would it be possible to instrument Tangram (ES/JS) to keep track of how many tiles were downloaded and the sum of the fractional areas of those which intersected the view box?

That, along with target screen sizes, would give us some hard data to work with and figure out what the actual cost / benefit would be of changing tile sizes.

**Comment by bcamper** [comment]
We can look a measuring % of tiles that are actually on screen. I think for Tangram, most of the benefit would be from reduced GL draw call overhead, which would be 4x less for wholly covered tiles and somewhere between 1-4x for partially covered tiles. So better sense of the exact coverage difference would be useful for knowing the latter -- is that what you had in mind? We may be able to measure that directly by counting the number of GL state change (uniforms, texture bindings, etc.) and draw calls we would save.

On the server side, wouldn't this also mean a 4x reduction in the number of tiles we have to generate and store (for renderers that support this scheme anyway, which includes Mapbox)? For example if we are still overzooming past z16, but each tile now covers four times the amount of screen space...

In any case, screen sizes have gotten considerably bigger since the days that the 256px size was chosen, it seems overdue for a re-evaluation so I think Mapbox has had the right idea here (and from my understanding some other companies that do this internally as well).

**Comment by zerebubuth** [comment]
I assume that tiles are only fetched if they intersect the viewport, so I was interested in what proportion of the tile was downloaded in excess of what was needed. For example, if the screen is exactly one tile in size and there's no perfect alignment then it's likely that 4 tiles will be downloaded, meaning a 300% bloat in the network traffic over the absolute minimum required to render the same scene (e.g: with a WMS-like call).

To keep things simple, I'll assume a square screen. If the screen is about 2 tiles wide, then we'd expect to waste 125%, 4 tiles 56%, 8 tiles 27% - but with the number of requests increasing with the square of the number of tiles.

If someone pans the screen, or zooms out fractionally within the current zoom, then the wastage figures will drop as the tiles will get used. And I was interested if we could find some real data about how much that happens in order to evaluate different tile sizes under different operating assumptions.

**Comment by bcamper** [comment]
Yes it should be possible to calculate how many tiles would be generated
under different tile + screen size combinations... though now we've
hijacked this issue into being about tile size, so I'll refrain for now and
we can open an issue for it when we have more to post :)

**Comment by nvkelso** [comment]
512 px tiles are working well for us, closing.
