### ISSUE TITLE
dev has some broken water, land at zoom 5

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1030]
This was also a problem in v1.0.0-pre1 tiles, persists in v1.0.0-pre2.

* **What did you see?** Missing tiles over UK and Spain at zoom 5; missing water/land in Baltic.
* **What did you expect to see?** Content.
* **What map location are you having problems with?** #5/55.066/8.438
* **Screenshot?** 

<img width="932" alt="screen shot 2016-09-08 at 08 38 48" src="https://cloud.githubusercontent.com/assets/853051/18355982/dee1036c-759f-11e6-9a12-ac9be261297d.png">

**Comment by nvkelso** [comment]
Also the Caspian:

5/38.462/60.073

<img width="596" alt="screen shot 2016-09-08 at 08 52 29" src="https://cloud.githubusercontent.com/assets/853051/18356478/a0dc151e-75a1-11e6-8728-537ff52aa684.png">

**Comment by nvkelso** [comment]
Africa 5/12.447/-0.352

<img width="771" alt="screen shot 2016-09-08 at 08 53 23" src="https://cloud.githubusercontent.com/assets/853051/18356504/be6b64ae-75a1-11e6-8d7c-7565b94717ce.png">

**Comment by nvkelso** [comment]
Another piece of missing land (not tile) 5/27.936/-99.712:

<img width="482" alt="screen shot 2016-09-08 at 08 54 02" src="https://cloud.githubusercontent.com/assets/853051/18356529/d7ccb088-75a1-11e6-88d7-25c5fbbd3540.png">

**Comment by nvkelso** [comment]
Asia missing land chunks 5/54.304/-202.148:

<img width="963" alt="screen shot 2016-09-08 at 08 56 32" src="https://cloud.githubusercontent.com/assets/853051/18356595/302d54a8-75a2-11e6-994c-66837fcf1aec.png">

**Comment by nvkelso** [comment]
5/6.948/-249.126

<img width="896" alt="screen shot 2016-09-08 at 08 57 47" src="https://cloud.githubusercontent.com/assets/853051/18356635/615f015c-75a2-11e6-8093-4bdb955d4861.png">

**Comment by nvkelso** [comment]
Missing tiles seems to get better on zoom (with the problem geom still failing just 1 or 2 child tiles instead of all 4 child tiles).

**Comment by nvkelso** [comment]
Some of the missing land / water does resolve on zoom in, some does not?

**Comment by zerebubuth** [comment]
I'm seeing things like:

```
Error handling request for /all/5/16/11.mvt: Traceback (most recent call last): 
   File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 195, in __call__    response = self.handle_request(request) 
   File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 298, in handle_request    [], [], self.buffer_cfg) 
   File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 358, in process_coord    feature_layers, extra_data = _preprocess_data(feature_layers) 
   File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 63, in _preprocess_data    shape = loads(wkb) 
   File "/usr/local/lib/python2.7/dist-packages/shapely/wkb.py", line 16, in loads    return reader.read(data) 
   File "/usr/local/lib/python2.7/dist-packages/shapely/geos.py", line 361, in read    raise ReadingError("Could not create geometry because of errors " 
 ReadingError: Could not create geometry because of errors while reading input.
```

in the logs. It seems like the WKB coming from the database is invalid. I'm wondering if it's connected to #963 or the changes in tilezen/tilequeue#107 and either this is something that we used to discard disrupting the whole process, or we're getting invalid geometries by clipping instead of pulling back the whole geometry from the database.

**Comment by zerebubuth** [comment]
@iandees and I tried to figure out what was going wrong, and found some other errors along the way:

1. The Caspian sea appears to to be missing from the `ne_10m_ocean-merc.shp` that I have locally. Need to download the latest bundle of shapefiles and check whether it's missing from those too, but this seems like it might be a data error - perhaps the Caspian sea didn't survive projection to Mercator?
2. The Baltic around Gotland (tile 5/17/9) generates fine locally and on dev when it's JSON format. The problem seems to be when it's MVT, which suggests perhaps the conversion to integer coordinates is causing it to become invalid. This should trigger an attempt to call `makeValid` on it, but perhaps that's not helping - or the operation is discarding some parts of the multipolygon.
3. The tile 5/15/10 was failing completely on dev, but works fine locally. On dev it gives 504s from apiaxle, or times out when running locally on a tileserver machine. No errors are logged in pgbouncer or tileserver.

So that's at least 3 separate errors - perhaps 4 including the stack trace above!

**Comment by rmarianski** [comment]
> The Caspian sea appears to to be missing from the ne_10m_ocean-merc.shp that I have locally. Need to download the latest bundle of shapefiles and check whether it's missing from those too, but this seems like it might be a data error - perhaps the Caspian sea didn't survive projection to Mercator?

This looks to be caused by the [-wrapdateline](https://github.com/tilezen/vector-datasource/blob/9fabd57d5713964aa4859493fb787fe28e325523/data/Makefile-prepare-data.jinja2#L25) option. I remember @zerebubuth asking me to take that out, but I must have missed making that change. I'll reproject everything again without that option and update the shape files on s3.

**Comment by zerebubuth** [comment]
@rob's change in #1038 fixed the Caspian Sea issue.

The missing Baltic Sea comes down to this:

![fjords](https://cloud.githubusercontent.com/assets/271360/18554658/d1f2808c-7b5c-11e6-9fe6-9ab7214fa33d.png)

Both the red and blue polygons are in the JSON, but the blue one becomes invalid when quantized to the integer coordinates required for MVT (there's a very, very small self-crossing [around here](http://www.openstreetmap.org/#map=13/60.0621/18.7663)) making it a bow-tie and calling `buffer(0)` on it makes it choose the smaller part of the bow-tie. The rest of the Baltic Sea is discarded.

It seems to help if the polygon is oriented the opposite way before the buffer takes place. We could perhaps detect the large reduction in area and reverse the polygon and try again?

**Comment by nvkelso** [comment]
+1

**Comment by nvkelso** [comment]
Almost all of these are fixed now!

But I found a few more. I don't consider them ship blockers (I only found these 3), filed a new issue which we should resolve in a v1.0.1 patch: https://github.com/tilezen/vector-datasource/issues/1072
