### ISSUE TITLE
Update not equals filter rule

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1043]
The not equals filter rule should be updated to first check that the tag exists before checking the inequality, similar to how the equals rule works.

**Comment by zerebubuth** [comment]
I had to do this for `SetRule` before as well. Should we just extend it to cover all the rules?

**Comment by rmarianski** [comment]
> I had to do this for SetRule before as well. Should we just extend it to cover all the rules?

Is there a way to extend it generically to all rules? Seems like the equals, not equals, set, and existence rules are the ones that need it, and the others are either combinators or it's not relevant.

**Comment by zerebubuth** [comment]
Do we need it for the `GreaterOrEqualsRule` too?

One possible way to do it would be in the combinators, as that's where the problem actually arises. For example, if we have `tags->'foo' >= 0 OR tags->'bar' in ('a', 'b')` then the problem is when `'foo'` doesn't exist and `'bar'` might be `'a'`, then the whole expression returns NULL as the first term is NULL. We could swap the OR check for `case when $first then true when $second then true else false end`? Then we wouldn't need the exists checks... I think?

**Comment by rmarianski** [comment]
> Do we need it for the GreaterOrEqualsRule too?

In theory yes, but not in practice because all the tags are strings and the only places that we use these rules are when we know we have numeric values.

> One possible way to do it would be in the combinators, as that's where the problem actually arises.

I see what you mean. I suppose we just need a function that converts the result to a boolean where null is false, and we can call that on the results in the combinators. I feel like ensuring that we always return a boolean in the leaf rules is more intuitive though.

**Comment by zerebubuth** [comment]
I agree that it's more intuitive to do it in the leaves. And I guess `COALESCE($test, false)` does what we want, and would be fewer tests than doing the check first? Or, perhaps `COALESCE($test, true)` where it's a negative test?

**Comment by nvkelso** [comment]
Related to building filters in https://github.com/tilezen/vector-datasource/pull/1036.
