### ISSUE TITLE
Missing water near Oakland, Calif at zoom 12

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1075]
* **What did you see?** No water in bay.
* **What did you expect to see?** Should see water in bay.
* **What map location are you having problems with?** 12/37.8197/-122.2957 (Oakland, Calif.)
* **Screenshot?** 

<img width="433" alt="screen shot 2016-09-22 at 00 28 39" src="https://cloud.githubusercontent.com/assets/853051/18739937/c6c5c4cc-805b-11e6-83bf-bc00e2ace1fb.png">

**Comment by nvkelso** [comment]
It's fine at zooms 11 and 13, though?!

**Comment by nvkelso** [comment]
Poking around other cities I don't see a repeat. If this is obvious let's fix, else punt for a patch update.

**Comment by zerebubuth** [comment]
After initial investigation, it seems the JSON tile is fine, suggesting this is related to tilezen/mapbox-vector-tile#45 and tilezen/mapbox-vector-tile#66. The MVT tile does contain the ocean feature, but just this bit of it:

![image](https://cloud.githubusercontent.com/assets/271360/18747320/9ae89532-80c4-11e6-90f9-db1b404173d1.png)

(MVT is cyan, JSON is magenta). That's around here on the full tile:

![image](https://cloud.githubusercontent.com/assets/271360/18747389/fe2154b8-80c4-11e6-92c5-2e63c0d90fba.png)

I think this probably means that the fix in tilezen/mapbox-vector-tile#66 wasn't robust enough. 

Curiously, the MVT `water`-only tile (i.e: not `all` layers) is okay, and displays fine, but I think that's just because `tileserver` hasn't been updated to the same code as `tilequeue` yet?

**Comment by rmarianski** [comment]
>Curiously, the MVT water-only tile (i.e: not all layers) is okay, and displays fine, but I think that's just because tileserver hasn't been updated to the same code as tilequeue yet?

Ah, yes. Just updated it now.

**Comment by nvkelso** [comment]
Is this a dup of #1072?

Some SF water was fixed, but other areas of land & water broke. See other issue for screenshots.

**Comment by nvkelso** [comment]
💯Verified all fixed on dev!
