### ISSUE TITLE
Vector tile source "osm" layer "water" does not use vector tile spec v2 and therefore may have some rendering errors.

### ISSUE THREAD

**Issue by musicformellons** [tilezen/vector-datasource#1086]
I get these error messages (for several layers) in the browser console with a stylesheet that used to work fine couple of months ago:
"Vector tile source "osm" layer "water" does not use vector tile spec v2 and therefore may have some rendering errors."

Possibly related to this:
https://github.com/osm2vectortiles/osm2vectortiles/issues/388

Any solution?

**Comment by nvkelso** [comment]
Hi @musicformellons, sorry to hear you're having problems. I suspect it's because of a new strict topology check on the geometry in the tiles that Mapbox GL performs. The v2 Mapbox Vector Tile format is very strict about this, even though for rendering the map it's often fine. 

We have made some progress in being v2 MVT compliment in our v1 Mapzen Vector Tiles which are currently available on our development server. Please have a look and see if they work better for you:

* **GeoJSON:** `http://tile.dev.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.json`
* **TopoJSON:** `http://tile.dev.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson`
* **Mapbox Vector Tile:** `http://tile.dev.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.mvt`

If you're still having problems, I recommend checking out Tangram from Mapzen, it's a solid map rendering library.

**Comment by musicformellons** [comment]
Thanks for your explanation and suggestions. Development gives same messages seems to me, so I will stick to 'production' server. Messages do not give any obvious rendering issues. Always nice to be compliant though!

**Comment by nvkelso** [comment]
Closing this issue. Work to be fully MVT `v2` compliant is covered over here: https://github.com/tilezen/mapbox-vector-tile/issues/42
