### ISSUE TITLE
Merge water and earth polygons

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1106]
- **What did you see?**

![image](https://cloud.githubusercontent.com/assets/271360/19397173/991e934c-923e-11e6-9c3e-bc55093e08e9.png)
- **What did you expect to see?**

Similar, but without the red horizontal and vertical lines.
- **What map location are you having problems with?**

The example above is New York City, but the problem should be evident globally.

We should probably merge the water and earth polygons to get rid of (most of) these seams. (The ones near property changes would remain, e.g: `sea`/`ocean`) It would also make the tiles smaller.

Related #735, /cc @meetar.

**Comment by nvkelso** [comment]
Related to #1107

**Comment by rmarianski** [comment]
The background here is that we used to union the general earth and water queries, and grouped by their properties, but we had to switch to using json instead of hstore, and the version of postgresql we were using at the time didn't support grouping by json.

Since we're using postgresql 9.5 now, we could go back to grouping by it in sql, but that would mean that we require 9.5 to run the tile stack.

Instead, we can do the merging and grouping in python. Transforms should exist to already did this, if not out of the box, close to it. We merge polygons for the buildings and landuse layers.

**Comment by nvkelso** [comment]
I’d like to do this at the python Transform post processing layer so we
don’t need to bump the Postgres requirement.

**Comment by iandees** [comment]
How can I test this? @zerebubuth, what style are you looking at in that screenshot?

**Comment by nvkelso** [comment]
@iandees Try Peter's tag explorer:

- http://tangrams.github.io/explorer/#10.0/40.6233/-73.4422/kind/ocean
- http://tangrams.github.io/explorer/#10.0/40.6233/-73.4422/kind/earth

**Comment by pnorman** [comment]
> The background here is that we used to union the general earth and water queries, and grouped by their properties, but we had to switch to using json instead of hstore, and the version of postgresql we were using at the time didn't support grouping by json.

You should be able to pick a field out of the json and group by that, but I think it's better to do this in post-processing.

**Comment by nvkelso** [comment]
Verified fix on dev using custom Bubble Wrap and in Ikeda, one of the Sandbox styles where this issue was originally reported.

- Ikeda tested with this variant (load into Tangram Play): https://api.github.com/gists/3bba222b99804ccbf81a1188d9f01d45

<img width="597" alt="screen shot 2016-11-11 at 09 09 30" src="https://cloud.githubusercontent.com/assets/853051/20223444/954f7c5c-a7ee-11e6-957b-2a663352922c.png">
<img width="604" alt="screen shot 2016-11-11 at 09 09 22" src="https://cloud.githubusercontent.com/assets/853051/20223447/959a00ec-a7ee-11e6-9993-5ae8276aadff.png">
<img width="942" alt="screen shot 2016-11-11 at 09 02 00" src="https://cloud.githubusercontent.com/assets/853051/20223446/95993450-a7ee-11e6-96c5-1b52279bb1a9.png">
<img width="935" alt="screen shot 2016-11-11 at 09 01 48" src="https://cloud.githubusercontent.com/assets/853051/20223445/959920d2-a7ee-11e6-9696-3e8f5e58290e.png">
