### ISSUE TITLE
Missing island in lake

### ISSUE THREAD

**Issue by aAXEe** [tilezen/vector-datasource#1109]
I think I found a problem in the vector tiles:

* **What did you see?**
An island inside a lake is not considered as "land": http://tangrams.github.io/bubble-wrap/#17.49525/53.62168/11.41502
See also screenshot below.

* **What did you expect to see?**
Land: http://www.openstreetmap.org/?mlat=53.62179&mlon=11.41396#map=18/53.62179/11.41396&layers=D

* **What map location are you having problems with?** 
This way should be considered as land: http://www.openstreetmap.org/way/30454499
See also: http://tangrams.github.io/explorer/#18.0/53.6218/11.4142/id/70191373

![screen_bubble_wrap_7 24525-53 62170-11 41450](https://cloud.githubusercontent.com/assets/3298652/19486995/f41eba72-9560-11e6-86af-d59cb09a9ed9.png)

**Comment by zerebubuth** [comment]
I think what's happening here is that the [outer way](http://www.openstreetmap.org/way/70191373) of the [Burgsee multipolygon relation](http://www.openstreetmap.org/relation/152021) is tagged `name=Burgsee, natural=water, wikipedia=de:Burgsee (Schwerin)`. The software we are using to make the rendering database, [`osm2pgsql`](https://github.com/openstreetmap/osm2pgsql), sees that the outer way has different tags to the multipolygon relation, and conservatively leaves both features in the database. This means that the outer way creates a polygon without a hole which renders over the top of the park.

This doesn't happen on the main OSM rendering, as the database there is not set up to keep the `wikipedia` tag, so `osm2pgsql` can identify the outer way as not being a feature in its own right.

I think the issue here is that the data in OSM should not have any tags on the outer way, and the relation should gain the `wikipedia=de:Burgsee (Schwerin)` tag.

**Comment by zerebubuth** [comment]
I've made that change in [changeset 43005056](http://www.openstreetmap.org/changeset/43005056). The change should be visible in the vector tiles in a few hours time.

**Comment by aAXEe** [comment]
It works. Thank you very much!
