### ISSUE TITLE
Clip buildings

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#1142]
Buildings are clipped at [3x3 tile boundaries](https://github.com/tilezen/vector-datasource/blob/1ab3ebadcf4c8fa5eab3ef55d2d0e6ed6cb003a2/queries.yaml#L107), and has its own side effects, alpha issues? cc @meetar @bcamper 

We should try clipping buildings like other features on dev to see if that introduces any artifacts.

**Comment by nvkelso** [comment]
What's the context on this one? Is there a related Tangram or Mapzen basemap issue?

**Comment by nvkelso** [comment]
Possibly related: https://github.com/tangrams/tangram/pull/455#issuecomment-266453180

**Comment by meetar** [comment]
Context: long ago the buildings were clipped to tile boundaries, but this caused artifacts in Tangram, so buildings which crossed tile boundaries were duplicated into each tile it touched, then eventually clipped again at the 3x3 tile boundary, because of the [High Line problem](https://github.com/tilezen/vector-datasource/issues/197).

We were discussing various benefits of trying clipping, partially because of [the issue mentioned above](https://github.com/tangrams/tangram/pull/455#issuecomment-266453180)☝️, and are curious whether the artifacts seen long ago would still be seen.

**Comment by nvkelso** [comment]
Subtask of https://github.com/tilezen/vector-datasource/issues/1348.
