### ISSUE TITLE
[docs] add highest zoom levels

### ISSUE THREAD

**Issue by kkowalsky** [tilezen/vector-datasource#1161]
we do a good job of documenting where the switch over from Natural Earth to OSM occurs at zoom 8, but we should describe what the highest zoom level is

**Comment by nvkelso** [comment]
Like zoom 16?

**Comment by kkowalsky** [comment]
here's @hanbyulhere's example that we should clarify: 

"ex. I am overlaying custom tile over our vector tile and thought our vector tile's highest zoom is 16.
I prepared the custom tiles up  to 16 and found out it doesn't really align with our vector tile when the map is zoomed more than 16"

**Comment by nvkelso** [comment]
Currently our default `max_zoom` hosted service config is setup to to be
zoom 16 and we recommend people "over zoom” client side (both Tangram and
MapboxGL have convenience properties for this). For clients like D3 and
Unity we currently allow server-based over zooming where if the client
requests a zoom 17 tile the server will over zoom it. This is not a
efficient code path, though.

I’ll followup with Hanbul to find out about "I prepared the custom tiles up
to 16 and found out it doesn't really align with our vector tile when the
map is zoomed more than 16”.

**Comment by hanbyul-here** [comment]
I think this screenshot would explain what I meant. Colored buildings are from my custom tiles. 

<img width="742" alt="screen shot 2017-01-31 at 9 13 04 am" src="https://cloud.githubusercontent.com/assets/4583806/22468430/3b6436c8-e796-11e6-8414-155f575e4645.png">

You can see that it is not aligning with roads from Mapzen Vector Tiles. I wondered this happened because two tile sets zoom level are not same. (While vector tile has higher resolution than zoom 16 , custom one interpolates from zoom 16.) 

Since @nvkelso mentioned that our tile maxzoom is 16, maybe some this is happening from othere reasons.( road style of basemap styles can be too thick for this data? etc..)  

but still, it would be good to document this!

**Comment by nvkelso** [comment]
We can document suggested "maximum" `{z}` values of **16** (for default 256px tiles) and **15** (for optional 512px tiles) in https://github.com/tilezen/vector-datasource/blob/master/docs/use-service.md#use-the-vector-tile-service.

But we shouldn't add details to address @hanbyul-here's comment in https://github.com/tilezen/vector-datasource/issues/1161#issuecomment-276375792 – that's just a natural artifact of combining different sources which different quality issues. There are things we could do in Mapzen basemaps to style the roads thinner at high zooms to reduce the overlap – but some of the overlap is likely due to miss-classification of the roads in OpenStreetMap and miss-match in geometry digitization details between the sources (I suspect the buildings are higher quality and OSM should move around the roads).

**Comment by hanbyul-here** [comment]
Yess I agree with @nvkelso . I think it will be still useful for users to know when Mapzen tiles become interpolated (zoom 16).
