### ISSUE TITLE
Gaza Strip Border Issue

### ISSUE THREAD

**Issue by kkowalsky** [tilezen/vector-datasource#1257]
* **What did you see?**
![screen shot 2017-05-22 at 5 52 08 pm](https://cloud.githubusercontent.com/assets/4246770/26334160/d569d358-3f17-11e7-85e5-6663f426138b.png)

* **What did you expect to see?**
It looks like the northern border of the Gaza Strip is being clipped 

* **What map location are you having problems with?** 
Northern border of Gaza Strip

**Comment by nvkelso** [comment]
@stepps00 Can you investigate, please?

I suspect this is because of funk in our maritime boundaries mask:

- https://tangrams.github.io/explorer/#11.0/31.7512/34.5843/maritime_boundary/true

See red lines:

<img width="799" alt="screen shot 2017-05-22 at 23 00 21" src="https://cloud.githubusercontent.com/assets/853051/26336794/798e2220-3f42-11e7-9605-ae730b36d7fa.png">

**Comment by stepps00** [comment]
@nvkelso - this bug is due to the `buffered_land_10272016.shp` file not extending to cover the entire Gaza Strip border (work done in #294). A screenshot of the polygon area as displayed in QGIS, below:

<img width="947" alt="screen shot 2017-05-23 at 10 09 35 am" src="https://cloud.githubusercontent.com/assets/18567700/26366465/0ebfe7ea-3fa0-11e7-8b35-b9760b2287a9.png">

The fix should be to simply cover the border area, as shown below:

<img width="950" alt="screen shot 2017-05-23 at 10 14 18 am" src="https://cloud.githubusercontent.com/assets/18567700/26366620/9e0531b2-3fa0-11e7-876e-4ca9f227f0a2.png">

I have a new `buffered_land_05232017.shp` file ready to swap in as a replacement for the existing buffer - should this be delivered through S3?

**Comment by nvkelso** [comment]
@stepps00 yes, delivery via S3 works for me (like in https://github.com/tilezen/vector-datasource/issues/294#issuecomment-256815733).

**Comment by kkowalsky** [comment]
yay!

**Comment by stepps00** [comment]
Shapefile ready for the next build is in S3 ([here](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/buffered_land_05232017.zip)).

Compressed file includes the following:
- **buffered_land_05232017.shp** - File that should replace whatever `buffered_land` file is currently being used.

`buffered_land_05232017.shp` size: ~**7.6MB**

**Comment by nvkelso** [comment]
We should also update the water / land data from osmdata.com to fix the Texas & etc coastline problems.
