### ISSUE TITLE
column "mz_water_min_zoom" does not exist

### ISSUE THREAD

**Issue by dphiffer** [tilezen/vector-datasource#1264]
I ran into this issue after going through the [Mapzen Vector Tile Service](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service) setup guide.

This is with vector-tilesource v1.4.0, tileserver v2.1.0, and tilequeue v1.8.0.

```
$ python tileserver/__init__.py config.yaml
 * Running on http://localhost:8080/
 * Restarting with reloader
127.0.0.1 - - [04/Jun/2017 18:34:39] "GET /buildings/16/19293/24641.json HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/mapzen/tileserver/tileserver/__init__.py", line 148, in __call__
    response = self.handle_request(request)
  File "/usr/local/mapzen/tileserver/tileserver/__init__.py", line 226, in handle_request
    nominal_zoom, unpadded_bounds, self.layer_config.all_layers)
  File "/usr/local/mapzen/tileserver/env/lib/python2.7/site-packages/tilequeue/query.py", line 215, in __call__
    raise async_exception
ProgrammingError: column "mz_water_min_zoom" does not exist
LINE 28:     mz_water_min_zoom as min_zoom,
```

When I ran `perform-sql-updates.sh` I got the following output:
https://gist.github.com/dphiffer/8056dca5f1c26fa409278bfc5e7f54ca

And before that, when I ran `import-shapefiles.sh ` I got this:
https://gist.github.com/dphiffer/f2d681bc8e41454d3b5cc0d64b6dcb06

**Comment by zerebubuth** [comment]
The error seems to be related to these lines in the `perform-sql-updates.sh` output:

```
psql:apply-schema-update.sql:2: ERROR:  must be owner of relation planet_osm_polygon
...
psql:apply-schema-update.sql:9: ERROR:  must be owner of relation planet_osm_line
...
psql:apply-schema-update.sql:16: ERROR:  must be owner of relation planet_osm_point
...
```

Which suggests that the `osm` user might not own those tables. It looks like the command line in our setup guide doesn't specify `-U`, but simply notes:

> You may also need to pass in other options, like -U or -W, to ensure that you connect to the database with a user that has the appropriate permissions.

I wonder if it would make more sense for a single-user install if we assumed that the user who was doing the import was the database user (i.e: `whoami`), and used PostgreSQL's built-in `ident` auth support for local users. That might simplify the instructions and make permissions errors less likely? @rmarianski, what do you think?

@dphiffer in the meantime, you might need to run `ALTER TABLE planet_osm_xxx OWNER TO osm;` for each of those three tables and go back to the `perform-sql-updates.sh` step. For what it's worth, I've been using my local user rather than `osm` when I do local database imports.

**Comment by rmarianski** [comment]
> I wonder if it would make more sense for a single-user install if we assumed that the user who was doing the import was the database user (i.e: whoami), and used PostgreSQL's built-in ident auth support for local users. That might simplify the instructions and make permissions errors less likely? @rmarianski, what do you think?

That sounds good to me. Is there a way we can detect this, and emit a better error message at import time too?

**Comment by dphiffer** [comment]
Thanks @zerebubuth & @rmarianski! I ended up running out of disk space on my laptop, but I'll give this a try when I get things back into shape.

**Comment by nvkelso** [comment]
I recommend a metro extract instead of planet ;)

**Comment by dphiffer** [comment]
Ok, I tried redoing this as a single-user Postgres user and it worked! Thanks all. I also edited the wiki page to help the next person (maybe me!).
