### ISSUE TITLE
include access in road layer

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1273]
* **What did you see?**
https://mapzen.com/documentation/vector-tiles/layers/#roads-transportation is not mentioning access field for roads, for access=private roads inspect in https://mapzen.com/tangram/play/?#17.75000/50.07917/19.89074 is not listing any value that indicates it. Searching in https://mapzen.com/documentation/vector-tiles/layers/#roads-transportation for private, destination and similar reveals nothing.

* **What did you expect to see?**
Access, fundamental values for roads is an exposed attribute.

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

For example at https://www.openstreetmap.org/#map=19/50.07918/19.91407

**Comment by matkoniecz** [comment]
Is it fixable in way similar to https://github.com/tilezen/vector-datasource/commit/2c3edbbaed6aaeaf4d0306f75d1609b239af27e0 ?

**Comment by nvkelso** [comment]
@matkoniecz Yes, it'd be a similar enhancement (no architecture changes). The bulk of the time is writing the integration test and waiting for CircleCI to bless the change. Want to submit a PR?

> (though that commit has surprising surface: {col: sport} - why sport?)

That looks like a mistake that's was later fixed in master: 

- https://github.com/tilezen/vector-datasource/blob/master/yaml/roads.yaml#L24

**Comment by nvkelso** [comment]
Subtask of https://github.com/tilezen/vector-datasource/issues/1349.
