### ISSUE TITLE
Buildings not rendering on Mapzen

### ISSUE THREAD

**Issue by dbdean** [tilezen/vector-datasource#1363]
* **What did you see?**
Similar to Issue #1320, There are no buildings showing up in the MapZen layers in StreetComplete. Have confirmed with the online mapzen demo maps too.
![screenshot from 2017-08-04 08-59-36](https://user-images.githubusercontent.com/12725310/28947880-a3b90596-78f5-11e7-8dd0-ace8bb6bdb52.png)
* **What did you expect to see?**
Buildings, like here in openstreetmap: http://www.openstreetmap.org/#map=17/-27.40443/153.05618
![screenshot from 2017-08-04 09-00-00](https://user-images.githubusercontent.com/12725310/28947916-ca1703a0-78f5-11e7-8625-37f62f036309.png)

* **What map location are you having problems with?** Brisbane, Australia -> http://www.openstreetmap.org/#map=17/-27.40443/153.05618

**Comment by nvkelso** [comment]
@dbdean Are these recently added buildings or from a changeset around the same time as the other missing (but since restored) changeset?

**Comment by dbdean** [comment]
It looks like they were largely added in a series of changests by user 'Ian TF' around a month ago. Here's one example: http://www.openstreetmap.org/changeset/49828275.

**Comment by dbdean** [comment]
It looks like it is an earlier series of changesets than the previous issue, as they were between changeset 50298898 and changeset 50403909, and these appear to be earlier than that.

**Comment by zerebubuth** [comment]
I think this is probably the same as #1320, but by the time I came to investigate it looks like it fixed itself:

![image](https://user-images.githubusercontent.com/271360/28966694-9883b54e-790f-11e7-92d7-937ef48c4eb9.png)

The tile `15/30315/18979` now has a last-modified time of Fri, 04 Aug 2017 10:29:30 GMT, which could plausibly have been added to the TOI and rendered at the 10am run of the gardener. Given that several of us have been looking around that area, it might have made it into the "most viewed tiles" list and been rendered - which means we lost all the information about the previous (perhaps stuck) state of the tile.

This is what I see for Walkabout now, more zoomed-in because it shows buildings a bit later than Bubble Wrap:

![image](https://user-images.githubusercontent.com/271360/28966743-c17fbcb8-790f-11e7-8505-52a08629b509.png)

Please do let us know if you find any more of these!

**Comment by dbdean** [comment]
@zerebubuth, Thanks for looking into this. I can confirm the buildings are showing now, and I'll close this issue. Thanks!
