### ISSUE TITLE
Roads not returned in GeoJSON

### ISSUE THREAD

**Issue by Noshire** [tilezen/vector-datasource#1476]
* **What did you see?**

Our own tilezen instance (built from 1.4.0) never returns road data. Other data is returned as expected (POIs etc.). This behaviour is consistent across all filters( `all/`, `roads/` etc.).

I've checked the source `.osm.pbf` data (extracted to `.osm` and scanned for `<way>` nodes and searched for specific road names that are returned by one example query, see below), and all the data is there.

Our vector-datasource also contains all the `ne_10m_roads-merc.*` files, totalling at about 40MB, which sounds reasonable.

I checked the `roads.jinja2` query. Everything looks reasonable (and we didn't touch anything from the 1.4.0).
One thing I've noticed is that several sources mention a `config.yaml` in `vector-datasource/`, but we don't have one (only` test_config.example.yaml`). However, I wasn't sure from what I could gather around the docs and threads whether this config is entirely replaced by the contents of the `vector-datasource/yaml/` folder plus `queries.yaml` in 1.4.0, or if we'd still need to create a config.

I didn't build and deploy it myself I'm afraid, but I'll do my best to provide insights if any additional info is required.

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

Sample query against MapZen: 
https://tile.mapzen.com/mapzen/vector/v1/roads/16/34320/22946.json?api_key=yourkeyhere

returns (correctly):
[output_mapzen_public.txt](https://github.com/tilezen/vector-datasource/files/1694983/output_mapzen_public.txt)
(~54 roads)

The same query against our own tileserver instance:
http://localhost:8080/roads/16/34320/22946.json

returns (incorrectly):
`{"type":"FeatureCollection","features":[]}`
(0 roads)

* **Conclusion**
I browsed the open issues and other sources, and didn't really find anything related to this issue. Two individual coworkers of my company have set up tilezen instances independently of each other, both following the guide under https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service, and both server instances have the same issue. Any help would be very appreciated, thanks!

**Comment by zerebubuth** [comment]
It's possible that the process to set up the database tables hasn't worked properly. Please could you run the following against your database to check if it has set the `mz_road_level` "min zoom" property?

```sql
select mz_road_level from planet_osm_line where osm_id = 429114139;
```

(That's for [a section of Sihlquai](https://www.openstreetmap.org/way/429114139), which should get a min zoom of 11.)

If that is `NULL` or the column doesn't even exist, then it's likely that something in [the SQL updates for `planet_osm_line` didn't work](https://github.com/tilezen/vector-datasource/blob/v1.4.0-docs2/data/apply-planet_osm_line.sql#L8-L10) and you can try re-running that query.

If the query fails, or seems to run but still produces `NULL`s, then the issue might be with the `mz_calculate_min_zoom_roads` function, which is [generated from YAML files](https://github.com/tilezen/vector-datasource/blob/v1.4.0-docs2/data/perform-sql-updates.sh#L21-L23) (not CSV, as the comment suggests). You can run that on its own, or without the pipe into `psql`, and see if there's something failing there too.

Hope that helps! Let us know how you get on. 😄

**Comment by Noshire** [comment]
Thank you for the quick reply! It would seem that, while the DB definitely contains ways, your query indeed returns no results:

> osm=# SELECT COUNT(*) FROM planet_osm_ways;
>   count
> 
>  44913943
> (1 row)

> osm=# select mz_road_level from planet_osm_line where osm_id = 429114139;
>  mz_road_level
> 
> (0 rows)

I'm now running the recommended update routine to update all the mz_road_levels. It's running since about 2h on the dataset of germany+switzerland, guess that's normal? I'll report back as soon as I know more, thanks for the help!

**Comment by zerebubuth** [comment]
Ah! I wasn't expecting zero results... That's interesting. It would suggest that way 429114139 either wasn't in the original extract or the import process failed to import it. Since there are several ways called "Sihlquai", you might need to grep for `way id="429114139"`. You could also try looking for way 554005030, in case that's present in the database and 429114139 got cut off somehow?

That query does take a very long time to run, and 2h seems about right. It has to write to every entry in the `planet_osm_line` table, which means a lot of disk I/O.

**Comment by Noshire** [comment]
I've let it run overnight, still didn't return with anything. I've cancelled it for now, as it's improbable that it would take that long for the given area.

I've checked the original data source zurich_switzerland.osm (not sure about the source), and it definitely contains 	<way id="429114139"(...)> , so I guess something went wrong when importing into the db. I'll check with my colleague who's set it up and we might try re-running the import process and see if anything's amiss there, thanks for the help!

**Comment by zerebubuth** [comment]
Two possibilities come to mind:

1. Osm2pgsql didn't consider the road to be a feature, so wasn't importing it. This could be due to problems with the "style" file, if you're not using the one which comes with vector-datasource.
2. A bug or different behaviour between osm2pgsql versions. The version I use locally is very, very old, but works for my needs. It's commit `0.90.0-RC1-78-g1f62bd0` from https://github.com/rmarianski/osm2pgsql/tree/mz-integration.

Re-running a whole import can be a long way of tracking down a problem. I'd recommend downloading the way with its nodes from https://www.openstreetmap.org/api/0.6/way/429114139/full and importing that instead of the extract. It should be almost instantaneous, and won't produce much output, making it easier to see if there are any errors in osm2pgsql's output, PostgreSQL's logs, or the output of the Tilezen scripts.

Good luck!

**Comment by kurtyka** [comment]
Hello zerebubuth,

I am the other co-worker, did another setup with a smaller set of data around Zürich. Thanks for pointing out the possible failure points. Reviewing your comments and re-running the SQL updates for planet_osm_line I found the following error: 

> ... vector-datasource/data$ ./perform-sql-updates.sh -d osm -U xyz
> Creating custom schema...
> Password for user xyz:
> psql:schema.sql:6: ERROR:  relation "wof_neighbourhood_placetype" already exists
> psql:schema.sql:12: ERROR:  duplicate key value violates unique constraint "wof_neighbourhood_placetype_pkey"
> DETAIL:  Key (placetype_code)=(1) already exists.
> psql:schema.sql:30: ERROR:  relation "wof_neighbourhood" already exists
> psql:schema.sql:32: ERROR:  relation "wof_neighbourhood_label_position_index" already exists
> psql:schema.sql:33: ERROR:  relation "wof_neighbourhood_min_zoom_index" already exists
> psql:schema.sql:34: ERROR:  relation "wof_neighbourhood_max_zoom_index" already exists
> psql:schema.sql:40: ERROR:  relation "mz_pending_path_major_route" already exists
> done.
> Creating functions...

The same querry for mz_zoom level also returns empty.

I have tried the create-sql-functions.py without piping it to psql, it printed the sql scripts basically. When I try to pipe it to psql I got a bunch of errors: 

> BEGIN
> ERROR:  type geometry does not exist
> ERROR:  current transaction is aborted, commands ignored until end of transaction block
> ERROR:  current transaction is aborted, commands ignored until end of transaction block
> ERROR:  current transaction is aborted, commands ignored until end of transaction block


Any ideas where to look for? Really much appreciated!

**Comment by kurtyka** [comment]
I did run the create sql functions on a not correct db, that I rerun now and also the update, which produced a new unseen log: 
psql:apply-planet_osm_point.sql:49: ERROR:  relation "planet_osm_point_min_zoom_pois_index" already exists
CONTEXT:  SQL statement "CREATE INDEX planet_osm_point_min_zoom_pois_index ON planet_osm_point USING gist(way) WHERE mz_poi_min_zoom IS NOT NULL"
PL/pgSQL function inline_code_block line 28 at SQL statement

Hope this could help, thanks a lot!

**Comment by zerebubuth** [comment]
Hi @kurtyka,

> psql:schema.sql:6: ERROR: relation "wof_neighbourhood_placetype" already exists

Ah, I've seen this one a bunch of times. It usually means that I forgot to completely clear the database, so it wasn't empty and still had tables left over from the last run. Usually, I do

```
dropdb whatever
createdb -E UTF-8 -O `whoami` whatever
psql -d whatever -c 'CREATE EXTENSION postgis; CREATE EXTENSION hstore;'
```

just to make sure that the database is completely fresh!

> psql:apply-planet_osm_point.sql:49: ERROR: relation "planet_osm_point_min_zoom_pois_index" already exists

This probably means the same - the database wasn't empty, and still had this index left over from the previous run.

> ERROR: type geometry does not exist

That's unexpected! Did you run `CREATE EXTENSION postgis;` to load the PostGIS extension into that database? If so, what versions of PostgreSQL and PostGIS do you have? Are you able to run `create temporary table test_geometry (the_geom geometry);` without errors?

Hope that helps!

**Comment by kurtyka** [comment]
Hi @zerebubuth,

Thanks a lot, I'm starting now again with a new db. I was able to create extensions for both. It is working perfectly fine! I was able to import region Zürich and its a bit different than MapZen, but I think thats because of new data was added (content is more). Made a comparison on some id-s and they were exactly the same. 

My new question is: how should I do the process to import Germany is well? Using the '-a' switch to import with osm2pgsql ? Or start from scratch, import both and then run the table scripts? I guess  the second option is the way, just want to get a confimation! 

It definately helped, many thanks again 🥇

**Comment by zerebubuth** [comment]
Glad I could help!

The safest way would be to combine the extracts with [osmosis](https://wiki.openstreetmap.org/wiki/Osmosis) first or, if you don't mind importing Austria as well, there's [a DACH extract](http://download.geofabrik.de/europe/dach.html) which might be easier than getting osmosis to work.

Importing one and then the other (with `-a`) should work too, I think... But I haven't done that for regions which share nodes/ways at the border, so I don't know if it's 100% safe.

Definitely only run the table scripts once. It's possible to import stuff after the table scripts have been run, but it'll be much slower as it has to keep the indexes up to date and run the triggers. There's also some hassle around the `mz_pending_path_major_route` table which it's easier to avoid if you don't need to do updates!

**Comment by kurtyka** [comment]
That might be a bit of a bigger chunk for us to process and support since our application only focuses and region D and we need a really small portion of CH to be covered - and that is a small rectangle not bordering to part of D. What I noticed is running with '-a' is definately slower after something is already in the DB, so I'm starting with Germany and then adding our small rect later. Will let you know if it is good and thanks again!

**Comment by kurtyka** [comment]
We managed to solve this issue, and we consider it to be closeable.

**Comment by zerebubuth** [comment]
Great news! Thanks for letting us know. I hope the rest of the process is trouble-free!

**Comment by kurtyka** [comment]
[not related to the topic here] 
Thanks @zerebubuth, maybe could you point us into a direction how to optimize the response time of requests? Its pretty slow basically after setting up the whole thing. Is it postgresql? Or the tilequeue of some config? We did give some more memory to postgre, but yet it still slow. CPU is relatively low during requests 1-2%, might be disk slow or any other idea? What you guys usually do to speed things up for production? Please let me know how else or where to talk about this topic.
