### ISSUE TITLE
CI builds failing

### ISSUE THREAD

**Issue by pnorman** [tilezen/vector-datasource#1478]
The CI builds are failing with 
```
ConnectionError: HTTPConnectionPool(host='54.164.172.53', port=80): Max retries exceeded with url: /api/interpreter?data=%28node%283573482149%29%3B%29%3Bout%3B (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8835cff190>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

My recollection is that Mapzen was running its own Overpass server for stuff like this, and it's probably shut down now. I don't see that particular IP in the codebase, perhaps it's coming directly from the CircleCI configuration?

**Comment by zerebubuth** [comment]
Thanks for pointing that out! The Overpass configuration, as you thought, comes from the CircleCI environment and isn't present in the source. Since we no longer have that server, I've reset it to the default, public Overpass instance. The latest master [seems to be passing OK](https://circleci.com/gh/tilezen/vector-datasource/2319).

If we get any particularly large changes then it could go over the acceptable level of use for the public Overpass server. It would probably be better to stand up a new instance under Nextzen. What do you think, @nvkelso?

**Comment by pnorman** [comment]
> If we get any particularly large changes then it could go over the acceptable level of use for the public Overpass server. It would probably be better to stand up a new instance under Nextzen. What do you think, @nvkelso?

We're caching, aren't we? As long as  `aws s3 sync ~/.cache/vector-datasource/ s3://mapzen-tiles-assets/integration-test-fixtures/ --size-only --exclude="*" --include="*.geojson"` is working it should be fine.

We should rebuild the cache, see #1470

**Comment by zerebubuth** [comment]
> We're caching, aren't we?

Yes, I meant that if we make any test changes that would require pulling in a lot of new data that weren't already cached (e.g: large routes).

> We should rebuild the cache

That looks like it needs code changes to bring the code "up to date" with the real world. This has been a constant annoyance since we started basing tests on real data. I'd favour us going back and changing those tests to use synthetic, generated or checked-in (stale) data.

**Comment by nvkelso** [comment]
No longer an issue, closing.
