### ISSUE TITLE
How is the shapefile being generated?

### ISSUE THREAD

**Issue by guyisra** [tilezen/vector-datasource#1540]
Currently the shapefile.tar.gz is a static url taken from tilezen-assets bucket.

Is the shapefile a mapzen/tilezen a creation for mapzen/tilezen proprietery sources or is it from open source? How is it being generated? what is it and when should it be updated?

**Comment by zerebubuth** [comment]
The `shapefiles.tar.gz` is a combination of sources, the full list is in [`data/assets.yaml`](https://github.com/tilezen/vector-datasource/blob/108db28921496b68989524f85c39f5751246c56a/data/assets.yaml). Everything bundled inside is open data, although some of it is manually generated or curated. The data comes from:

* `openstreetmapdata.com` for static land/water polygons.
* `naturalearthdata.com` for various themes used at low zooms.
* `admin_areas` is based on OSM data and available under the ODbL. It gets generated by manually running [Valhalla's `mjolnir` tool](https://github.com/valhalla/valhalla/blob/master/docs/mjolnir/admins.md) occasionally.
* `buffered_land` is based on OSM data and available under the ODbL. It is manually curated by Tilezen and is a slightly buffered land polygon to clip admin boundaries against so that we don't get admin boundaries going off into the sea. See #294 and #1257 for examples and more details.

Related question: #1112

`shapefiles.tar.gz` is generated by running:

```
cd data
python bootstrap.py
make -f Makefile-prepare-data
```

Although this can take a very long time to download all the individual pieces!

**Comment by nvkelso** [comment]
Note the buffered_land is actually from Natural Earth.

Added this information to the Wiki in https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service/15e3675f89bc15980c9c9cff2a3759043c52d02c and closing this issue.

**Comment by nvkelso** [comment]
Oh, right. I forgot we did that. So what did you start with in https://github.com/tilezen/vector-datasource/issues/210#issuecomment-144452490 as prototype 3? Was that OSM or Natural Earth?

**Comment by zerebubuth** [comment]
I found an original version of `buffered_land` lying around (from Oct 2015), and it matches `ne_50m_land` from the same time (sadly missing version, I'm guessing around v3.0?).

I'm not sure why there's `OSM_ID` or `ADMIN_LEVE` attributes on the most current one - the original only has `FEATURECLA` and `SCALERANK` (which has presumably been dropped along the way).

**Comment by zerebubuth** [comment]
![image](https://user-images.githubusercontent.com/271360/41715302-e241e218-754a-11e8-8116-f25ee6f398f9.png)

`ne_50m_land` in blue, with `buffered_land` outlined in red. Screenshot is of around [Tierra del Fuego](https://www.openstreetmap.org/#map=7/-54.817/-68.143).
