### ISSUE TITLE
Fewer places at low zoom.

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1687]
The `0/0/0` tile contains:

* 91 countries,
* 744 regions,
* 25 localities.

We couldn't possibly render all of these in a single tile, so we should remove some of them. The properties on these features are the major contributor to size of tiles at zooms 3 and lower.

**Comment by nvkelso** [comment]
From https://github.com/tilezen/vector-datasource/issues/1684:

Let's use the min_zoom on country, region, and locality features from Natural Earth to drop labels.

In particular country labels don't all need to be shown at low zooms, just a few handful. There's a **label min_zoom** separate from feature min_zoom for this.

**Comment by nvkelso** [comment]
For 1/41/-74...

New:

![image](https://user-images.githubusercontent.com/853051/49972101-7e9d3d00-fee5-11e8-9b37-4cb0e7ea5f59.png)

Old:

![image](https://user-images.githubusercontent.com/853051/49972127-85c44b00-fee5-11e8-94be-cefa291c14c9.png)

**Comment by nvkelso** [comment]
**0/43/-73**

For zoom 0 we're still including too many countries, I'll file followup issue. Seems like we're doing 512 min_zoom math instead of 256 math? Like at zoom 0 we should only see features with min_zoom < 1, but many 1.x graded features are included.

New:
![image](https://user-images.githubusercontent.com/853051/49972295-10a54580-fee6-11e8-98d7-8dc8e84df513.png)


Old:
![image](https://user-images.githubusercontent.com/853051/49972286-07b47400-fee6-11e8-8baa-fa0a3b3b50f6.png)

![image](https://user-images.githubusercontent.com/853051/49972360-40544d80-fee6-11e8-9a52-125b52dbaacb.png)
`

**Comment by nvkelso** [comment]
Generally this is working to significantly reduce file size... but we're still over stuffed. Followup in https://github.com/tilezen/vector-datasource/issues/1729.

For zoom 0 we're still including too many countries. The same is true for zooms 1 and 2. Addressing this will have significant file size savings.

Seems like we're doing 512 min_zoom math instead of 256 math? Like at zoom 0 we should only see features with min_zoom < 1, but many 1.x graded features are included.

New:
![image](https://user-images.githubusercontent.com/853051/49972295-10a54580-fee6-11e8-98d7-8dc8e84df513.png)


Old:
![image](https://user-images.githubusercontent.com/853051/49972286-07b47400-fee6-11e8-8baa-fa0a3b3b50f6.png)

![image](https://user-images.githubusercontent.com/853051/49972360-40544d80-fee6-11e8-9a52-125b52dbaacb.png)
`
Poland is included at zoom 2, but it's min_zoom is 3.

![image](https://user-images.githubusercontent.com/853051/49972840-ba390680-fee7-11e8-910b-f17bc33dd465.png)

**Comment by nvkelso** [comment]
Closing in favor of tiny bit of followup in https://github.com/tilezen/vector-datasource/issues/1729.
