### ISSUE TITLE
Further places layer plastic surgery

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#1729]
_Originally posted by @nvkelso in https://github.com/tilezen/vector-datasource/issue_comments#issuecomment-447149749_

For zoom 0 we're still including too many countries. The same is true for zooms 1 and 2. Addressing this will have significant file size savings.

Seems like we're doing 512 min_zoom math instead of 256 math? Like at zoom 0 we should only see features with min_zoom < 1, but many 1.x graded features are included.

New:
![image](https://user-images.githubusercontent.com/853051/49972295-10a54580-fee6-11e8-98d7-8dc8e84df513.png)

Old:
![image](https://user-images.githubusercontent.com/853051/49972286-07b47400-fee6-11e8-8baa-fa0a3b3b50f6.png)

![image](https://user-images.githubusercontent.com/853051/49972360-40544d80-fee6-11e8-9a52-125b52dbaacb.png)
`

Poland is included at zoom 2, but it's min_zoom is 3.

![image](https://user-images.githubusercontent.com/853051/49972840-ba390680-fee7-11e8-910b-f17bc33dd465.png)

**Comment by nvkelso** [comment]
Probably this line can change:

https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/transform.py#L8132

>             if min_zoom is not None and min_zoom <= nominal_zoom + 1:

to:

>            if min_zoom is not None and min_zoom <= nominal_zoom:

**Comment by zerebubuth** [comment]
> Seems like we're doing 512 min_zoom math instead of 256 math? Like at zoom 0 we should only see features with min_zoom < 1

Our 512px tiles are designed to contain the same content as the 4 `z+1` 256px tiles which cover the same area. Therefore, the nominal zoom (i.e: style zoom) of a 512px tile is `z+1`. So the nominal zoom of the `0/0/0` 512px tile is 1.

Also, because clients typically overzoom a zoom `N` tile for zooms `<N+1`, we designed the tile to contain things with a min zoom up to `N+1`. Therefore, the `0/0/0` tile would contain, for example, features with a `min_zoom` of 1.9 because the `0/0/0` tile is the one being displayed when the nominal zoom is 1.9.

I'm happy to make a change as suggested (basically dropping a whole bunch of features needed for overzooming), but we should be aware that it'll be a major change compared with how we've done things in the past. Although it might not matter, if clients aren't evaluating fractional zooms anyway.

**Comment by nvkelso** [comment]
Verified, closing.
