### ISSUE TITLE
DataFetchException wikidata

### ISSUE THREAD

**Issue by rwrx** [tilezen/vector-datasource#1915]
Congratulations on releasing v1.8.0. I have imported slovakia.osm.pbf, performed vectordatasource import, run tileserver and on zoom 10 and higher I am getting exception on tileserver: DataFetchException: column "wikidata" does not exist LINE 15: 'wikidata', wikidata. How can I fix this? I am not sure which table(s) in postgres I should check for presence of wikidata column.

**Comment by nvkelso** [comment]
@zerebubuth can you take a look, please?

**Comment by zerebubuth** [comment]
I think this is coming from the [WOF query](https://github.com/tilezen/vector-datasource/blob/583a6234bccdea363abbee1ac5082cd11333db37/queries/wof.jinja2#L15).

In the 1.8 release we [changed how WOF data is loaded](https://github.com/tilezen/vector-datasource/pull/1889); instead of downloading the `.pgdump`, we now bundle a WOF dump with the static assets and it doesn't need an additional step to import. It's possible that the `.pgdump` might have been loaded over the top of the static asset version, and this left the table "missing" a column.

Looking at the [documentation](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#load-whos-on-first-neighbourhood-data) and [changelog](https://github.com/tilezen/vector-datasource/blob/master/docs/CHANGELOG.md#internal-changes), I think we probably didn't highlight this change enough. Sorry! What can we do to make this clearer?

**Comment by nvkelso** [comment]
@rwrx does starting with a new DB fix this for you?

**Comment by rwrx** [comment]
I am sorry for this late answer, I took me some time to test it. Yes, it does fix the issue, I haven't updated my vector-datasource import scripts. Thank you a lot for your support.

**Comment by nvkelso** [comment]
@rwrx Great to hear it works for you now :)
