### ISSUE TITLE
README rate limits link: 404

### ISSUE THREAD

**Issue by meetar** [tilezen/vector-datasource#1947]
The link [API keys and rate limits](docs/api-keys-and-rate-limits.md) in README.md is 404 – is there current documentation of rate limits?

**Comment by nvkelso** [comment]
Mapzen doesn't offer a live service anymore, and these docs were written with that service is mind so that page was removed when the project moved to the Linux Foundation to reduce confusion.

That said, https://developers.nextzen.org/ does offer a live service, you can signup for API keys. The rate limits are whatever Lambda can sustain... but is meant for small demo projects not live commercial traffic. For that you'd want to stand up your own Tapalcatl server on Lambda. Happy to discuss more!

**Comment by nvkelso** [comment]
I should also note the Nextzen endpoint is funded for 6-9 more months, we're looking to secure more funding so do get in touch if that's an issue for you ;)

**Comment by meetar** [comment]
Thanks Nathaniel!
