### ISSUE TITLE
Rips in water-land in Puget Sound

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#427]
There are small inconsistencies in how the water and land make it into tiles, particularly zoom 9 and 10:

http://tangrams.github.io/cinnabar-style-more-labels/#9/48.6828/-123.6401

At first these were thought to be bad filtering server side [#407](https://github.com/mapzen/vector-datasource/issues/407), but that turned out to be bad scene file filtering (fixed). But after fixing that there are still small rips along the coastline where white shows thru. File this in the rainy day bucket.

<img width="1053" alt="screen shot 2015-12-07 at 21 11 51" src="https://cloud.githubusercontent.com/assets/853051/11648308/e046dfb6-9d27-11e5-8ade-36015967228e.png">

**Comment by zerebubuth** [comment]
I'm 99% sure that what's going on here is due to simplification. We have 2 polygon sources, the water and land, which should be gap-free as originals but will likely simplify differently, leaving overlaps and gaps. These are very tiny, as our tolerance is 1px, which means that a point can be dropped if it's 0.99px away from the line between its next and previous points, leaving a "splinter" of a gap.

This would be improved, but not fixed, by #131 as it would limit the area rather than the width of the splinter. We could also reduce the tolerance to reduce the visual impact.

A possible work-around is the common approach of rendering either land as a background colour with water on top, or vice-versa. Because only one set of polygons is rendered, this ensures that there are no gaps. We provide both land and water polygons in the vector tiles, so this choice would be down to individual styles.

The real fix is the complicated one; preserving topology while simplifying.

**Comment by rmarianski** [comment]
Another quicker option that we've talked about implementing before is to derive the land geometry from water, ie `earth = tile-geom - water`. (I thought there was a ticket for this already but I'm not finding it now, so maybe not. Could have just been a comment on a different issue).

**Comment by nvkelso** [comment]
Is this a dup of https://github.com/mapzen/vector-datasource/issues/191?

**Comment by bcamper** [comment]
Rendering only land or water and leaving the other as background color
works for many traditional styles, but not cases where lighting or other
shader effects are applied. (I suppose we could optionally synthesize a
"background quad" covering the whole viewport to get lighting, but still
wouldn't cover all the desired cases.) IMO it's worth having properly
derived polygons for both land and water -- I like @rmarianski's idea.

On Tue, Apr 5, 2016 at 7:10 AM, Nathaniel V. KELSO <notifications@github.com

**Comment by nvkelso** [comment]
No longer _seams_ to be an issue, closing.

![image](https://user-images.githubusercontent.com/853051/52679448-f853a600-2ee9-11e9-8455-8af879a39edd.png)
