### ISSUE TITLE
Unify building parts with building

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#653]
In the `buildings` layer, it would be useful to know the building that all the parts were associated with. This can be done by seeing if the `building:part` overlaps a certain amount with any buildings in the
tile.

**Comment by nvkelso** [comment]
This can be tracked directly with the building relation per building part. SF example: [Ferry Building](http://www.openstreetmap.org/relation/6062613).

We added `root_relation_id` for transit stations in v0.9, let's reuse the property & extend the logic for buildings.

**Comment by rmarianski** [comment]
The problem is, at least in nyc, the buildings and their parts aren't always linked with a relation. For example: http://www.openstreetmap.org/way/160967745

**Comment by zerebubuth** [comment]
Yup, the logic required is more similar to #142. We might be able to use the "base" building outline as the "root ID", depends on whether we find that many building parts overlap multiple "base" buildings.

**Comment by nvkelso** [comment]
Related: https://github.com/tilezen/vector-datasource/pull/886

**Comment by nvkelso** [comment]
It's sounding like we should say `root_id` (and rename the transit `root_relation_id` to `root_id`).

**Comment by nvkelso** [comment]
@meetar I remember you were interested in this one? Can you please have a look at `dev` tiles to verify this one this week?

New source url setup to use is:

- `http://tile.dev.mapzen.com/vector/v1/all/{z}/{x}/{y}.mvt`

**Comment by meetar** [comment]
This is great news!

I see some things which make sense here, such as features with a `building_part: yes` tag plus a `root_id` tag pointing to the root feature.

But then I see some others which simply have an `osm_relation: 1` tag instead, such as the Bank of England building at http://tangrams.github.io/explorer/#17.0/51.5143/-0.0890/osm_relation/true:

<img width="571" alt="screen shot 2016-08-26 at 3 38 26 pm" src="https://cloud.githubusercontent.com/assets/459970/18018178/7c7743fe-6ba3-11e6-8762-82e7edc579e1.png">

In our tiles, the inner and outer shapes here seem to be split into two features, correlating to 
https://www.openstreetmap.org/way/4959510 and https://www.openstreetmap.org/relation/553472, but with no `root_id` or other node which would associate them with each other.

Should this kind of situation have been fixed in the changes mentioned above, or is this a separate issue?

**Comment by rmarianski** [comment]
So far it only unified building parts with the building they overlap with. Sounds like in addition to that logic, we'd want to also link buildings / parts to any relation that they are a part of? And I assume that we'd prefer to use any relation as the root id in ambiguous cases?

**Comment by zerebubuth** [comment]
Looks like there's a whole mess of things going on with the BoE building:

* [Relation 553472](https://www.openstreetmap.org/relation/553472) is a multipolygon relation, with `building=yes, amenity=bank` and `osm2pgsql` puts it in the polygons table.
* [Way 4959510](https://www.openstreetmap.org/way/4959510) is an outer of the above relation, but since it has different tags from its relation, (`building=public`), `osm2pgsql` cautiously retains it. This means there's a second polygon in the polygons table with the same outline as relation 553472 but without the holes.
* [Relation 2917677](https://www.openstreetmap.org/relation/2917677) is also present and although it doesn't have any tags itself, `osm2pgsql` processes it to "steal" the tags from its outer ([way 220644664](https://www.openstreetmap.org/way/220644664)), so it also ends up as a building.

I think we have two different issues here:

1. Relation 553472 and way 4959510 are both included as buildings due to a combination of tagging and how `osm2pgsql` interprets that tagging.
2. Relation 2917677 is an additional building on a similar footprint to relation 553472, which seems like it should be linked to the latter although it's not a `building:part`, and there's no relation linking them or containing them both (e.g: a "site" relation).

If this isn't a widespread problem, I'd be tempted to call it a data issue rather than introduce a special case to handle it. Although it would be nice to be able to present problems like this in a way that makes it easy for people to find and fix.

**Comment by meetar** [comment]
Ah ha – The tagging looked odd to me but I couldn't tell how, thanks for
unraveling it. I can do some more investigating to see how common that kind
of thing is, I believe I ran into a few others like it but I didn't keep
track… but I concur, adding ad hoc logic will give us an infinitely-long
rule set.

**Comment by rmarianski** [comment]
That all being said, if we had a relation with multiple buildings, would we want them all to be linked? As it stands now they will not be. The current logic will only link building parts with the largest overlapping building.

**Comment by nvkelso** [comment]
@rmarianski by relation with multiple buildings do you mean @zerebubuth's example Relation [553472](https://www.openstreetmap.org/relation/553472) as a multi polygon relation? I think we should add logic for that case.

**Comment by nvkelso** [comment]
I've verified Rob's basic work, let's split off the Bank of England work into a new ticket (https://github.com/tilezen/vector-datasource/issues/1032).

<img width="937" alt="screen shot 2016-09-08 at 23 13 35" src="https://cloud.githubusercontent.com/assets/853051/18377165/3b529758-761a-11e6-923f-e4d0202e9c16.png">

<img width="383" alt="screen shot 2016-09-08 at 23 13 48" src="https://cloud.githubusercontent.com/assets/853051/18377164/3b5103b6-761a-11e6-82bb-e5b127286120.png">

<img width="349" alt="screen shot 2016-09-08 at 23 14 11" src="https://cloud.githubusercontent.com/assets/853051/18377163/3b440710-761a-11e6-845d-f74d20035540.png">
