### ISSUE TITLE
Invalid geom in some tiles (GeoJSON)

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#698]
We've seen this a few times, and while Tangram mostly handles it okay, other tools barf on **invalid geometries**. 

Seems like the data is being transformed during vector tile creation (I suspect it's fine in PostGIS) and that transform results in self-intersecting geoms.

@wboykinm [reported](https://twitter.com/morganherlocker/status/718121546506575872) this on Twitter last week. He's been testing Mapzen vector tiles with Turf.js and found recurring examples of geometry errors for many metro areas. Superficially, he suspects feature simplification is causing some of this. 

**Here's an example:** 

* http://vector.mapzen.com/osm/water/13/1916/3387.json?api_key=vector-tiles-TE70otI. (The feature in question is id=362822667)

**More about the app:**

* https://github.com/wboykinm/tribes. 

Bill is trying to erase US census geometry with the Mapzen water geom using turf.js, see https://github.com/wboykinm/tribes/blob/mapzen/processing/water/piranha.js. 

PostGIS has ST_Makevalid() but Turf.js doesn't have a similar function so simple errors like self-intersecting polygons and non-noded intersections throw big unrecoverable errors that result in data loss.

Looks like Mapnik does some **OGC validation** in their tiles:

* http://mapnik.org/node-mapnik/documentation/3.5/#VectorTile.reportGeometryValidity

To find more invalid examples, Bill built a tool that tosses out self-intersecting polygons: https://www.npmjs.com/package/turf-bathwater. it'll also log the features that get thrown out.

**Comment by rmarianski** [comment]
It turns out that this is due to precision loss when we write the json out. @zerebubuth: what do you think we should do here?

**Comment by wboykinm** [comment]
@rmarianski Are you guys writing to a standardized decimal precision or is it zoom-dependent?

**Comment by zerebubuth** [comment]
The precision depends on the format and the zoom level. For GeoJSON (`.json` tiles), we change the number of [digits of precision by zoom level](https://github.com/mapzen/TileStache/blob/integration-1/TileStache/Goodies/VecTiles/geojson.py#L14-L17). For TopoJSON, MVT and OpenScienceMap, the coordinates within the tile are integers, so are inherently bounded by zoom level.

This is, indeed, a [well](https://github.com/mapzen/TileStache/issues/122) [travelled](https://github.com/mapzen/TileStache/commit/d14479b622b7195809a29ed89ff125a86652ac61) [path](https://github.com/mapzen/TileStache/commit/94a3c5bd5f6499d53231d79469940e46022b3ce5), and I'm not entirely sure what the best option is.

If we want only valid features in the tiles (which seems like a sensible thing to want), then we must do the validity checks after any encoding steps which would simplify or truncate precision (e.g: rounding to integers, truncating decimal places, dropping points due to movement tolerances). However, these steps are different for each output format, so we might end up dropping different features for each format, which could be confusing. Alternatively, we could encode all features in all formats and only output those features which are present in all formats - but this seems like a great deal of effort.

**Comment by nvkelso** [comment]
Related: http://www.angusj.com/delphi/clipper.php

**Comment by wboykinm** [comment]
#missioncreep

**Comment by rmarianski** [comment]
Based on a previous discussion, it sounds like we are willing to accept that different formats can contain differences in terms of content.

In this particular case of geojson encoding though, do we want to:

1. encode with truncated precisions based off zoom, make a decoding pass, and re-encode the invalid geometries with full precision?
2. encode with truncated precisions based off zoom, make a decoding pass, and drop the invalid geometries?
3. encode with truncated precisions based off zoom, try a decoding pass, and re-encode invalid geometries with buffer(0)?
4. always encode all features with full precision? (I'm assuming this option will never generate invalid features. But can it still with default json encoding?)

**Comment by wboykinm** [comment]
@rmarianski In hacking away at these geoms, I haven't actually had any luck with buffer(0) on the client side (`turf.buffer`, and the topology remains invalid). Do you mean to try that with PostGIS? And if so, is ST_Makevalid() too slow?

More broadly, I would encourage you folks to consider whether you even want to support a javascript, heavy-geoprocessing use case with your vector tiles. I'm within a few thrown errors of giving up on turf and moving my processing to PostGIS anyway, and you may not encounter this line of inquiry again for months/years.

**Comment by wboykinm** [comment]
@rmarianski UPDATE: I caved and tried using PostGIS to fix topology on [this particularly problematic water polygon](http://dropchop.io/?gist=61f99a6edc9da3ae788081b5ef6bfcf4) from [this Mapzen VT](http://vector.mapzen.com/osm/water/12/965/1689.json?api_key=vector-tiles-TE70otI), but neither `ST_Makevalid()` nor `ST_Buffer(0)` (or 100m for that matter) resolved the feature into a usable geometry. Some of these might just be intractable.

**Comment by wboykinm** [comment]
@nvkelso Does the merged PR above address the original problem? I can try running turf over it again if it'd be helpful.

**Comment by rmarianski** [comment]
It should address it yes. Running turf on it again would be helpful to know if it actually helped.

**Comment by nvkelso** [comment]
To set expectation, the fix will probably address many geom validity problems (and hopefully yours!) but not all geom problems. That is a Hard Problem (tm).

**Comment by nvkelso** [comment]
@rmarianski Anything more to test with this one before taking it to prod?

**Comment by rmarianski** [comment]
Should be good to go here.
