### ISSUE TITLE
Boundaries layer osm_relation value should be `yes` not `true`

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#778]
* `osm_relation`: `true`, which can also be deduced from negative `id` values.

Our convention is to use `yes`, not `true`.

**Comment by zerebubuth** [comment]
I think the use of `yes` (actually the string `"yes"`) is just historical accident following the normalisation of OSM's use of `yes`, `1` and `true` to all mean positive.

I find it a compelling argument for keeping `true` (not `"true"`, though), that JSON and MVT both natively support a boolean type. Using a boolean rather than a string hopefully makes it clearer to anyone consuming the data that it only has two values, unlike a string, and it can be stored more compactly.

Anywhere we're putting a `"yes"` value in the output tiles and we mean a boolean, I think we ought to convert it to a boolean type.

**Comment by nvkelso** [comment]
I'm good with converting the boolean `yes` values to `true`.

**Comment by zerebubuth** [comment]
I started doing some work on this and hit an annoying bump: `HSTORE` values can only be text, therefore cannot store booleans. This makes it difficult to pull boolean properties with the correct types out of the query.

An alternative way of doing things would be to keep `"yes"` as truth in the queries, and have a universal conversion of `"yes"` to `true` when we're decoding the row and `mz_properties`. The problem with that is that it might introduce mixed type values (e.g: with `true` and `"random other value"`).

Alternatively, we could specify this as a post-processing step for each layer, with the keys to convert to boolean explicitly set. It'a a little annoying (to me, at least) to do this as a final step, meaning we have to keep the `"yes"` values through the rest of the processing pipeline.

@rmarianski what do you think?

**Comment by rmarianski** [comment]
Instead of an hstore, can we use a json value as the result of the properties?

**Comment by zerebubuth** [comment]
@rmarianski - great idea, btw! Thanks for that. I thought I was at a dead end, but JSON(B) made #161 much easier to implement :smile:

**Comment by nvkelso** [comment]
👍
