### ISSUE TITLE
Reduce building payloads

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#845]
Buildings take up a large part of the tile payload. Let's reduce that footprint, (mostly at zoom 14). 

Options:

- Less features
- Dropping of attributes
- Normalizing of attributes
- Merging of features

**Comment by nvkelso** [comment]
@zerebubuth to share more stats here.

**Comment by bcamper** [comment]
I think it's nice to have all building footprints available at z14, but can
certainly see how we could merge or drop some things to slim it down.

**Comment by zerebubuth** [comment]
Using tile `14/4827/6161` as an example (because it tops the charts for largest building payload), it's composed of 8,785 separate features. Most of these are quadrilaterals, and have been previously simplified. Many have address, name and height info which is potentially unnecessary at z14, or can be quantized.

For example, here's a zoomed-in section of the original z14 tile:

![z14_buildings_before](https://cloud.githubusercontent.com/assets/271360/15515662/44014e9e-21e7-11e6-82ad-b3aacac656d8.png)

Notice that a lot of the buildings have been simplified to wedge shapes. This isn't terribly important for display at z14, as they're only a few px across, but mean that merging will be less effective than it would be were we to implement it before the simplification step.

![z14_buildings_after](https://cloud.githubusercontent.com/assets/271360/15515675/4dbc5028-21e7-11e6-8dd5-b58ad70f5abd.png)

Some of these rows of buildings can be merged into a single quad, potentially drastically reducing the number of separate features in a tile. However, this is only effective where we're dropping or quantizing some of the properties.

In this example, the number of features reduced from 8,785 to 3,848 and the tile size dropped from 3,396,886 to 934,595 (uncompressed GeoJSON). Savings post-compression would be less impressive, but I think more than compensated for by doing the merge pre-simplification.

The biggest **caveat** is that merging will be really obvious anywhere we're stroking the outlines of buildings. If that's stylistically important at z14 (which a quick check of our "headline" styles suggests it's not - most of these buildings are _not_ rendered at z14), then we need to think of something else.

**Comment by bcamper** [comment]
I'm curious about @meetar's thoughts here too from different demos (some of which have made more use of feature properties).

**Comment by meetar** [comment]
It's true, our "headline" styles haven't made much use of per-building attributes for styling so far, but I've been assuming others would, eventually. I've been looking forward to promoting Tangram as a data-visualization tool, with the vector tiles as the foundation – for instance, I'm tracking the LA buildings imports here: http://tangrams.github.io/explorer/#14.0/33.7910/-118.2878/kind/house – and the less data is available, the less we can do that. But maybe speed improvements are more valuable to us right now.

¯\\\_(ツ)\_/¯ I suppose we can always add it back in.

**Comment by nvkelso** [comment]
We're not proposing to take out all extra attributes on all buildings for all zooms. But because zoom 14 tiles are specifically too large in feature count and file size for our targets (good performance over mobile connection), we are proposing "generalizing" buildings at zoom 14 and less. The full set of attributes would still be available at zoom 16, and likely z15.  

There are a couple approaches to take for this, which we already employ for roads where roads where we strip out some details at early zooms and then merge individual features with common attributes into many multi-linestring / multi-polygon features (but with radically lower total feature count than the raw data). Hopefully there will still be enough attributes in there at zoom 14 so the map can display variety in buildings, but we need to do something now to address the large file size.

**Comment by bcamper** [comment]
I could see a middle-ground similar to our road merging, something like:

- Possibly fuse neighboring buildings together into "blocks", which could improve tessellation as well.
- Preserve properties relating to use/kind so that we can still style based on things such as residential/commercial/etc. (there may be other properties that are similarly desirable).
- Exclude features matching certain conditions, such as landmarks (whether that means buildings that have a name, or certain kind values, or some other property criteria).

**Comment by meetar** [comment]
Yep, that's as I understood it, and the rationale and proposed
methodologies are sound. And I agree that if we target mobile styling, then
a dataset suitable for interactive dataviz at z14 is inappropriately large.
I'm just pointing out the "if" in that sentence for the record.

It's the same problem which leads to the idea of two tilesets, one for
styling and one for analysis. Until that becomes less trouble than it's
worth, I'm sure there are even happier mediums possible in a single dataset
and I support improvements to performance. Those are my thoughts!

**Comment by nvkelso** [comment]
@zerebubuth has some ideas re @migurski's idea around different uses cases besides mobile tile display on a basemap that might still support data viz (of more things than just buildings).

**Comment by zerebubuth** [comment]
> I could see a middle-ground similar to our road merging, something like

Yup! That's what's being proposed. Most of these individual buildings are about 2px high, so are contributing little detail individually. By merging several together in a block (where properties permit), we should be able to provide fewer features with simpler geometries. But with a similar visual effect (caveat the stroking issue).

> And I agree that if we target mobile styling, then a dataset suitable for interactive dataviz at z14 is inappropriately large.

We don't have anything ready-to-use for custom (or at least customisable) vector tile sets yet (insert usual NEAT tiles rant here), so at the moment the choice of "support both" is harder than I'd like it to be.

The mean z14 tile across the sample is 140kB (69kB compressed), of which about 85% is building geometry and properties. A bare minimum 3G connection from a moving vehicle is ([according to Wikipedia](https://en.wikipedia.org/wiki/3G#Data_rates)) 48kbyte/s. Assuming we need at least 4 (probably 6 or more) tiles to cover the screen, that's 6 seconds to download them all - or less than a second to get only the non-building data. (Not including any extra latencies that the network / infrastructure might impose.)

As you point out; the question is **if** mobile use is important enough that we can accept optimisations for mobile that hurt other uses.

**Comment by nvkelso** [comment]
(something we could address with a bug fix later)

Seems to sometimes result in / joins within a building:

18/37.74474/-122.42590

<img width="680" alt="screen shot 2016-09-07 at 23 17 20" src="https://cloud.githubusercontent.com/assets/853051/18338950/3feab06c-7551-11e6-9abd-936ea71ed358.png">

18/37.73177/-122.48359

<img width="704" alt="screen shot 2016-09-07 at 23 18 09" src="https://cloud.githubusercontent.com/assets/853051/18338975/60e2abda-7551-11e6-96ee-76add7b93230.png">

**Comment by nvkelso** [comment]
Everything checks out but this one regression over prod (the weird line joins above are an existing bug on prod):

**Regression:**

**prod** has buildings in [13/1310/3170](http://vector.mapzen.com/osm/all/13/1310/3170.topojson?api_key=vector-tiles-HqUVidw)
**dev** is _missing_ buildings in [13/1310/3170](http://tile.dev.mapzen.com/vector/v1/all/13/1310/3170.topojson?api_key=vector-tiles-HqUVidw)

I suspect it's from this section in the YAML:

- https://github.com/tilezen/vector-datasource/blob/master/yaml/buildings.yaml#L35-L40

```
- &z13_area_volume
      all:
        any:
          way_area: { min: 1600 }
          volume: { min: 300000 }
        "tags->location": "-underground"
```

Which might be better stated as?

```
- &z13_area_volume
      all:
        any:
          way_area: { min: 1600 }
          volume: { min: 300000 }
        not: { "tags->location": "underground" }
```

Some fun screenshots showing `scale_rank` working:

<img width="1031" alt="screen shot 2016-09-08 at 22 18 48" src="https://cloud.githubusercontent.com/assets/853051/18376881/bfa7687e-7617-11e6-939d-27b3672ad982.png">

<img width="1079" alt="screen shot 2016-09-08 at 22 19 29" src="https://cloud.githubusercontent.com/assets/853051/18376882/bfa9a01c-7617-11e6-919a-9b18ecc9c16d.png">

**Comment by nvkelso** [comment]
Fix for z13 buildings is in https://github.com/tilezen/vector-datasource/pull/1036.

**Comment by migurski** [comment]
I have noticed that the scale rank on an individual building basis leads to some weird visual results with selective building rendering — makes areas look sparsely populated, even when they are densely packed with small buildings. Tippecanoe joins neighboring polygons and might be a mid-zoom approach we could adopt?

**Comment by nvkelso** [comment]
z13 buildings are back. The rest we can polish after v1.

@migurski sure, we can look at that (but once Geraldine is back, and after v1 release).
