### ISSUE TITLE
Add wikidata id concordance to features

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#858]
Customer request to add **wikidata ids** ~wikipedia links~ to features (in the POIs layer).

**Comment by nvkelso** [comment]
Some questions:

* Examples of Wikipedia OSM tags on POIs and other features
* What is the use case for the tags?
* Why limit this only to the POIs layer?

**Comment by zerebubuth** [comment]
Examples:

* [WMF offices](http://www.openstreetmap.org/node/2817389220)
* [Madison square park](http://www.openstreetmap.org/way/22899286)
* [Admiral Farragut Memorial](http://www.openstreetmap.org/node/1251496241)
* [The statue of Liberty](http://www.openstreetmap.org/way/32965412) - note that this also has `wikipedia:es` language variants, and a `wikidata` tag. We should bring those through too.
* [FDR Drive](http://www.openstreetmap.org/relation/109736) - not a POI, but has wikipedia info.

One interesting example that I expected to find, but did not appear to have a wikipedia tag, was [the famous bit of Lombard](http://www.openstreetmap.org/way/402111597). Opportunity for improvement.

I assume the use-case for the tags are to show extra information about the history or context of a particular object. To have a "more info" link which opens up a wikipedia page in another tab, for example. Or just to make it easier to collate the data for bundling into an offline tourist map, perhaps?

I think we should add this to all layers, although on layers other than POIs we probably want to remove the tag at mid zooms to avoid getting in the way of merging.

**Comment by erikschlegel** [comment]
I agree and mispoke about adding it to only the POI layer as places /
landmarks can span across the places / landuse / POI and other mapzen
vector layers. Our current use-case is that we're extracting points of
interest and places by using Mapzens vector tile service. In the event
where an openstreetmap POI has a wikipedia link, we provide users with the
ability to request for more information which is basically the first
paragraph from the intro in Wikipedia. I'm currently using Overpass as a
short-term workaround, until the vector service has the wikipedia tags
available. Great point on coalescing the variant wiki link tags into a
single field(i.e. wikipedia / wikipedia:es) similar to what you're doing
with the 'kind' field. This would be such an incredibly useful data set to
include in the vector tile service. My only concern about including a "more
info" link is that if the media wiki API service hosts changes then all the
links break, and also dealing with the multiple output types. Including the
wikipedia page title reference(s) into the Mapzen vector service would be a
great start.

All the best,

Erik

**Comment by zerebubuth** [comment]
Hi Erik,

Sorry if I wasn't clear - I meant to suggest passing through the `wikipedia` (and `wikipedia:*`) tags as they currently are in OSM, which is mostly page title references. As you say, it's better to use the page title not the link so that the client can construct the appropriate "more info" URL itself, or look up the content from a local device cache, or something else.

**Comment by erikschlegel** [comment]
Hey Matt,

Does the vector tile service provide the street intersection nodes by any
chance? If not, would the returned polyline shapes provide the intersecting
point(s) for 2 roads which happen to intersect?

All the best,

Erik

**Comment by zerebubuth** [comment]
Hi Erik,

Our tiles don't contain a separate point geometry for street intersections, although the point would normally be part of the linestring geometries of both the roads. I caveat "normally" because we currently simplify road geometries at zoom levels between 8 and 15 (inclusive), which may result in intersection points being elided if the road is mostly straight.

Would having separate point geometries with the main and cross street names be useful?

**Comment by nvkelso** [comment]
Verified:

![image](https://user-images.githubusercontent.com/853051/57430782-92737380-71e5-11e9-9d3c-c32dac4963fa.png)

![image](https://user-images.githubusercontent.com/853051/57430806-aa4af780-71e5-11e9-8803-876d0007c1e5.png)

**Comment by nvkelso** [comment]
Actually, looks like the WOF portion of this isn't totally working?

Western Addition should link to [Q7987437](https://www.wikidata.org/wiki/Q7987437) via WOF's [85856855](https://spelunker.whosonfirst.org/id/85856855/) concordance.

![image](https://user-images.githubusercontent.com/853051/57430927-09a90780-71e6-11e9-9039-e137ce9bf119.png)

**Comment by zerebubuth** [comment]
Thanks for checking that!

There's at least one bug: tilezen/raw_tiles#32

However, that should only affect high-zoom tiles, and we do include WOF neighbourhoods at z11, which I think should be generated directly from the database (because our metatile size means a nominal z11 tile is a z10 512px tile, which is generated from a z8 metatile/job). But an example (Miramar, San Diego) also shows no `wikidata_id`. So I'll need to do more debugging :confused:

**Comment by nvkelso** [comment]
Still missing wikidata_id from high zooms as reported in https://github.com/tilezen/vector-datasource/issues/858#issuecomment-490756801.

**Comment by zerebubuth** [comment]
:man_facepalming: 🤬 :boom: :interrobang: 

Looks like I forgot to click "merge" on tilezen/raw_tiles#32... D'oh!

I guess this means we won't be using the `v18e` build as 1.8 final :disappointed:, sorry.

**Comment by nvkelso** [comment]
Doh! Easy explanation, though :)

**Comment by nvkelso** [comment]
Verified in new build, closing.

![image](https://user-images.githubusercontent.com/853051/59075556-17ee5000-8886-11e9-83fa-4b7b11429386.png)
