### ISSUE TITLE
Convert integration tests from live data to static data artifacts

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#923]

**Comment by zerebubuth** [comment]
Adding some notes from discussion to help add detail:

* The `@` annotations specify the database content, bundled with each test. Using OSM content means downloading data from Overpass, running it through `osm2pgsql` and a long external toolchain. Instead, annotate the rows directly (WKT geometry in SRID 3875 plus hstore tags for the `planet_osm_*` tables).
* Is it possible to change the test harness to run the tests in a transaction which gets aborted, and use `tilequeue` directly rather than running via an external `test_server.py`?
* We probably need to make a tool which, given an OSM ID, outputs the rows which (did get written|would be written) to the database. That'll be useful for migrating the test cases and also for adding new tests in the future.
