### ISSUE TITLE
Remove -W UTF-8 from data import config

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#946]
`-W UTF-8` is probably not needed here: https://github.com/tilezen/vector-datasource/blob/master/data/Makefile-import-data.jinja2#L9

But might be version dependent, @zerebubuth to investigate and add details.

**Comment by zerebubuth** [comment]
I checked v2.1.2 (used in Ubuntu trusty) and v2.1.8 on my local machine, neither of which had problems with `-W UTF-8`, and they don't have the same issue with the encoding. However, UTF-8 is the default in all these versions, and appears to have been the default since 2.0.0 at least, possible before.

So it looks like we're safe to remove `-W UTF-8` wherever we find it, as we're unlikely to be running on that old a version of shp2pgsql. I'll put a check for that in, just in case.

**Comment by nvkelso** [comment]
Working.
