### ISSUE TITLE
Venice is under water

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#951]
* **What did you see?** Venice is under water, so is the island west of Athens.
* **What did you expect to see?** Roads should be on land.

We think this is caused because "land" kind sorts below water, but should instead sort above water.

**Comment by zerebubuth** [comment]
In the case of Venice, it's because [the Adriatic sea](http://www.openstreetmap.org/relation/4590486#map=13/45.4320/12.3353), which gets `kind:sea, sort_key:200`, covers Venice island, which is `kind:earth, sort_key:10`.

In the case of Salamina, near Athens, [the Aegean Sea](http://www.openstreetmap.org/relation/4594226#map=16/37.9543/23.5497), also `kind:sea, sort_key:200`, covers Salamina island, also `kind:earth, sort_key:10`.

If we alter the sort key of seas to be below earth, then we may get the opposite problem happening elsewhere in the world; bays which are part of seas "draining" because the land now "floats" above them. Related to #446.

There's another possible fix: both of these sea polygons come from a multipolygon tagged `place=sea` and, although it _is_ a polygon, perhaps it would be better to use it only for labelling as we already do for bays, straits and fjords #400 #515? In both cases above there were other polygons ([Venice Lagoon](http://www.openstreetmap.org/relation/3049430) and Salamina's coastline) which cover the water areas, without needing changes to the sort key.

**Comment by nvkelso** [comment]
When we added islands I made a bad assumption that their landmass would already be present in the earth data we get from openstreetmapdata.com (and they'd be cookie-cutttered with at least ocean-like water), so this logic removes their polygons (after creating label placements for them): https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L478-L484. 

Is another option to not remove island land features (to keep kind IN (`island`,`islet`) in the **earth** layer, and sort that above the water but below other man_made features? Example: https://www.openstreetmap.org/relation/2683672#map=18/45.42440/12.32811.

Looks like for seas we [generate label placements](https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L461-L465) but do not [drop the sea polygon](https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L466-L471). Seems like we need the sea polygon starting at the zoom we transition from NE to OSM, but we're always showing them from [zoom 3](https://github.com/tilezen/vector-datasource/blob/ea57f9a071aa9a6b9704451269e42ddf8d9b4c04/yaml/water.yaml#L137-L140) earlier now? Which is also creating tons of duplicate sea labels :\

**Comment by zerebubuth** [comment]
Venice is all land, from the `land_polygons` and `water_polygons` tables. The coastline is outside the lagoon, which is modelled as a large lake, so the "background" of the tile is all land.

Floating the island above the `place=sea` might lead to other issues, as there's other kinds of water on Venice island, for example Rio del Battello ([way 258639622](http://www.openstreetmap.org/way/258639622)) and this `natural=water` ([way 237920752](http://www.openstreetmap.org/way/237920752)), which need to be above the island. So now we've got at least 4 different layers: 

1. base earth,
2. "sea" water,
3. island earth,
4. non-"sea" water.

On the other hand, the lagoon ([relation 3049430](http://www.openstreetmap.org/relation/3049430)) _is_ cookie-cuttered, and has a hole for Venice island, which allows the land to show through. The problem is that the `place=sea` polygon for the Adriatic _isn't_ cookie-cuttered and covers the land. So dropping the `place=sea` polygon (but keeping the centroid for labelling) would solve the problem.

The story is similar for Salamina; it's covered by the Aegean polygon, but cookie-cuttered from the `water_polygons`, so it would render properly if the sea polygon were dropped.

I don't think we need the sea polygon at all.

**Comment by zerebubuth** [comment]
For what it's worth, I couldn't find anywhere in osm-carto where the polygon is rendered from `place=sea`.

**Comment by nvkelso** [comment]
**Less is more, agree we should drop sea polygons.**  _Also looking in osm-carto islands are only ever labeled and not rendered as land so I think we're fine there (except for performance issues)._

Looks like we add `sea` to list of water features here: https://github.com/tilezen/vector-datasource/blob/master/queries.yaml#L471

Let's track removing duplicate `sea` labels (e.g. Adriatic Sea, Adriatic Sea, Adriatic Sea) in https://github.com/tilezen/vector-datasource/issues/953.

/cc @burritojustice who originally reported this issue.

**Comment by nvkelso** [comment]
Working for Athens case!

dev
<img width="1385" alt="screen shot 2016-08-25 at 00 45 45" src="https://cloud.githubusercontent.com/assets/853051/17960871/58a2e8d0-6a5d-11e6-8262-645457f9cfdc.png">

prod
<img width="1383" alt="screen shot 2016-08-25 at 00 45 56" src="https://cloud.githubusercontent.com/assets/853051/17960870/58a0ca1e-6a5d-11e6-8ab9-8655091d8fc9.png">
