### ISSUE TITLE
Move centroid calculation to database

### ISSUE THREAD

**Issue by rmarianski** [tilezen/vector-datasource#965]
To generate labels on the python side, the original geometry was sent back from the database. This was adding network pressure on the database side to transmit large geometries back. Instead, we should clip at the database in these cases. However, this would affect the centroid calculation, so we should move this to the database. We can generate these at update time via a trigger.

**Comment by nvkelso** [comment]
This will also be a hotfix for the current v0.10.x series live in production.

**Comment by nvkelso** [comment]
This affected the following layer:

- `landuse`: this one is complicated to verify since we moved most the important landuse features over to the POIs layer, but it uses the same logic as water, earth, and buildings and those are working so "works for me".
- `water`: I still see lake labels
- `earth`: I still see island labels
- `buildings`: I see building labels (italic no icon)
